### ISSUE TITLE
Deprecation warning: Use of 'assign' has been deprecated

### ISSUE THREAD

**Issue by eelke** [sinankeskin/ember-swiper7#309]
Using this addon on Ember 4.7 renders the following deprecation warning: 

`DEPRECATION: Use of 'assign' has been deprecated. Please use `Object.assign` or the spread operator instead. [deprecation id: ember-polyfills.deprecate-assign] This will be removed in Ember 5.0.0. See https://deprecations.emberjs.com/v4.x/#toc_ember-polyfills-deprecate-assign for more details.`

**Comment by sinankeskin** [comment]
Hey @eelke I've just released v1.3.2 with fix. Should be ok now. Could you please check? Thanks.

**Comment by sinankeskin** [comment]
Cool. Glad to hear.
