### ISSUE TITLE
ember-swiper7/addon/controllers/application.js

### ISSUE THREAD

**Issue by BenjaminBeck** [sinankeskin/ember-swiper7#343]
Thanks for creating this addon!

I did some testing and think ember-swiper7/addon/controllers/application.js did override my applications controller. I don´t know much about ember addon development or if this is expected behaviour if you put a /controllers/application.js file in a addon..

The testing was done with ember 5 and embroider .. my problems might not apply to the supported env.

**Comment by sinankeskin** [comment]
I've just released v1.3.3. Could you please check?

**Comment by sinankeskin** [comment]
I assume this has been fixed. If not feel free to re-open. Thanks.
