### ISSUE TITLE
Does not work with Ember 5 (fix included)

### ISSUE THREAD

**Issue by eelke** [sinankeskin/ember-swiper7#344]
It seems the way you check for the existence of `ember-cli-sass` in [index.js](https://github.com/sinankeskin/ember-swiper7/blob/daf5b90831ef23e828a2fbc3d71e4cd5ba406eb9/index.js#L15) is no longer supported. 

Only by commenting out the whole `included(app)` method I could get the addon to run. 
The only other reference I could find to this issue was on the Discord, where @heroiceric asks about `ember-basic-dropdown` not working on Ember 5:

> TL;DR; app.registry.availablePlugins is undefined (example: https://github.com/cibernox/ember-basic-dropdown/blob/master/index.js#L15-L16C21) 
>
> I'm guessing availablePlugins was some kind of private API that was removed/replaced at some point but I'm not having any success finding any docs or anything that talk about it.

So I took a look at `ember-basic-dropdown`'s changelog, and found that from version 7.20 they support Ember 5. 
And there I found [the fix](https://github.com/cibernox/ember-basic-dropdown/commit/40e7659b19ce3e078eb3d28bb0afee973f975fe5#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346).

So, applied to your addon: If you replace your `included(app)` with this, it works again with Ember 5:

```js
included(app) {
    this._super.included.apply(this, arguments);

    const addons = app.project?.addonPackages || app.registry?.availablePlugins;
    const hasSass = !!addons['ember-cli-sass'];
    const hasLess = !!addons['ember-cli-less'];

    if (!hasSass && !hasLess) {
      app.import('node_modules/swiper/swiper.min.css');
    }
},

**Comment by eelke** [comment]
Pull-request created https://github.com/sinankeskin/ember-swiper7/pull/345

**Comment by sinankeskin** [comment]
I'm creating a new version now.

**Comment by sinankeskin** [comment]
v.1.3.4 has been released with your fix. Thank you so much.
